// examples/vue-ssr-extra/src/routes/page.vue
<script setup lang="ts">
import { ref, onMounted } from "vue";

const count = ref(0);
const hydrated = ref(false);

onMounted(() => {
  hydrated.value = true;
});
</script>

<template>
  <div>
    <div>hydrated: {{ hydrated }}</div>
    <div>Count: {{ count }}</div>
    <button type="button" @click="count--">-1</button>
    <button type="button" @click="count++">+1</button>
  </div>
</template>

// examples/react-ssr/src/routes/page.tsx
import React from "react";

export default function Page() {
  const [count, setCount] = React.useState(0);

  const [hydrated, setHydrated] = React.useState(false);
  React.useEffect(() => {
    setHydrated(true);
  }, []);

  return (
    <div>
      <div>hydrated: {String(hydrated)}</div>
      <div>Count: {count}</div>
      <button onClick={() => setCount((v) => v - 1)}>-1</button>
      <button onClick={() => setCount((v) => v + 1)}>+1</button>
    </div>
  );
}
